complete export_service_interface fn
Start9Labs/start-os pull request #2595
Opened 2024-04-08 02:52 UTC by Dominion5254

2024-04-18 20:46 UTC, dr-bonez commented
is this ready?

2024-04-20 20:41 UTC, Dominion5254 commented
I sent a message outside of GH, but yes, this PR is ready for review

2024-04-23 19:58 UTC, dr-bonez requested changes

2024-04-23 19:58 UTC, dr-bonez commented on core/startos/src/service/service_effect_handler.rs
> +            model.ser(&value)
use .insert on the model itself

2024-04-23 19:58 UTC, dr-bonez commented on core/startos/src/service/service_effect_handler.rs
> +    }
this match does nothing

2024-04-23 20:01 UTC, dr-bonez commented on core/startos/src/service/service_effect_handler.rs
> +            model.ser(&value)
https://github.com/Start9Labs/start-os/blob/next/minor/core/startos/src/db/prelude.rs#L250-L264

2024-04-24 19:29 UTC, dr-bonez requested changes
some more nitpicks

2024-04-24 19:29 UTC, dr-bonez commented on core/startos/src/service/service_effect_handler.rs
> +                .map(|_| ())
```suggestion
            db
                .as_public_mut()
                .as_package_data_mut()
                .as_idx_mut(&package_id)
                .or_not_found(&package_id)?
                .as_service_interfaces_mut()
                .insert(&svc_interface_id, &svc_interface_with_host_info)?;
            Ok(())
```

2024-04-24 19:29 UTC, dr-bonez commented on core/startos/src/service/service_effect_handler.rs
> +    let svc_interface_id = ServiceInterfaceId::from(Id::try_from(id)?);
take in the id as a ServiceInterfaceId instead of converting it

2024-04-24 19:29 UTC, dr-bonez commented on core/startos/src/service/service_effect_handler.rs
> +    let host_id = HostId::from(Id::try_from(address_info.host_id.clone())?);
same with HostId

2024-04-24 19:29 UTC, dr-bonez commented on core/startos/src/service/service_effect_handler.rs
> +    svc_interfaces_model.de()
```suggestion
    context
        .ctx
        .db
        .peek()
        .await
        .into_public()
        .into_package_data()
        .into_idx(&package_id)
        .or_not_found(&package_id)?
        .into_service_interfaces()
        .de()
```

2024-04-25 23:14 UTC, dr-bonez approved these changes

2024-04-25 23:16 UTC, merged