fix: fix build:deps command on Windows
Start9Labs/start-os pull request #2752
Opened 2024-10-04 08:35 UTC by waterplea

2024-10-16 17:47 UTC, dr-bonez requested changes

2024-10-16 17:47 UTC, dr-bonez commented on sdk/base/package.json
> +    "peggy": "peggy --allowed-start-rules * --plugin ./node_modules/ts-pegjs/dist/tspegjs -o lib/exver/exver.ts lib/exver/exver.pegjs",
the single quotes are required on unix

2024-10-16 17:47 UTC, dr-bonez commented on sdk/base/package.json
> +    "buildOutput": "npx prettier --write **/*.ts",
same here

2024-10-16 17:47 UTC, dr-bonez commented on sdk/package/package.json
> +    "buildOutput": "ts-node ./lib/test/makeOutput.ts && npx prettier --write **/*.ts",
same here

2024-10-16 18:52 UTC, dr-bonez commented
@waterplea can you explain why you needed to remove the quotes?

2024-10-17 04:53 UTC, waterplea commented
> @waterplea can you explain why you needed to remove the quotes?

It was failing on windows, saying no files matched the pattern, I believe.

2024-10-17 18:31 UTC, dr-bonez approved these changes

2024-10-17 18:33 UTC, merged