Fix: Error Messages in HealthCheck
Start9Labs/start-os pull request #2759
Opened 2024-10-18 19:40 UTC by Blu-J

Before
![image](https://github.com/user-attachments/assets/9afadbfa-727b-486b-a918-20b8f2571f6d)
After
![image](https://github.com/user-attachments/assets/74f36630-a7b5-442e-821b-daedc0edaabf)

2024-10-18 20:11 UTC, dr-bonez requested changes

2024-10-18 20:11 UTC, dr-bonez commented on sdk/package/lib/util/SubContainer.ts
>        (appendTo: { data: string | Buffer }) =>
```suggestion
      (appendTo: { data: string }) =>
```

2024-10-18 20:15 UTC, dr-bonez submitted a review, later dismissed

2024-10-18 20:28 UTC, MattDHill commented
We were also seeing this in "loading" state, not sure if this fix addresses that as well.

2024-10-21 20:46 UTC, MattDHill approved these changes

2024-10-21 20:47 UTC, merged