Fix/mac start cli packing
Start9Labs/start-os pull request #2767
Opened 2024-10-28 21:31 UTC by Blu-J

2024-10-28 21:33 UTC, Blu-J commented
We have it packing the system (in mac)
<img width="1249" alt="image" src="https://github.com/user-attachments/assets/d098dd8a-4933-4b05-a248-b2b28494a590">

Built the system
<img width="1270" alt="image" src="https://github.com/user-attachments/assets/6694d860-9803-44b9-b4e7-9d342520aafb">

Showing that the thing could be sideloaded
<img width="1642" alt="image" src="https://github.com/user-attachments/assets/09573987-869d-4ea3-9e69-9421d0e8278c">

2024-10-29 18:41 UTC, dr-bonez approved these changes

2024-10-29 18:42 UTC, dr-bonez requested changes

2024-10-29 18:42 UTC, dr-bonez commented on .github/workflows/sdk-utils.yaml
> +        if: ${{ inputs.publish_as_latest == 'true' }}
```suggestion
        if: ${{ inputs.publish_as_latest }}
```

2024-10-29 20:35 UTC, dr-bonez approved these changes

2024-10-29 20:38 UTC, merged