Feat/test smtp
Start9Labs/start-os pull request #2806
Opened 2024-12-27 17:43 UTC by Dominion5254

2024-12-27 21:01 UTC, kn0wmad commented on core/startos/src/system.rs
> +            .text_body("This is a test emails sent from your StartOS Server");
```suggestion
            .text_body("This is a test email sent from your StartOS Server");
```

2025-01-07 17:54 UTC, dr-bonez requested changes

2025-01-07 17:54 UTC, dr-bonez commented on core/startos/src/system.rs
> +    let _ = CryptoProvider::install_default(crypto_provider.clone());
```suggestion
    let _ = CryptoProvider::install_default(crypto_provider.clone());
```
does it not work without this? I would really like to avoid doing this

2025-01-09 20:43 UTC, dr-bonez approved these changes

2025-01-09 20:43 UTC, merged